# Generated by Django 3.1.4 on 2022-06-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_auto_20220516_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitios_visitados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lugar_que_visite', models.CharField(max_length=50)),
                ('Comentario_Bianca', models.CharField(default='Bianca todavia no realiza un comentario', max_length=400)),
                ('calificacion_Bianca', models.IntegerField(default=0)),
                ('Comentario_Axel', models.CharField(default='Axel todavia no realiza un comentario', max_length=400)),
                ('calificacion_Axel', models.IntegerField(default=0)),
            ],
        ),
    ]
